In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests

In [3]:
import json
from geopy.geocoders import Nominatim
from pandas.io.json import json_normalize
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
!pip install folium
import folium

Requirement already satisfied: folium in /opt/conda/envs/Python36/lib/python3.6/site-packages (0.11.0)
Requirement already satisfied: requests in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (2.21.0)
Requirement already satisfied: jinja2>=2.9 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (2.10)
Requirement already satisfied: branca>=0.3.0 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (0.4.1)
Requirement already satisfied: numpy in /opt/conda/envs/Python36/lib/python3.6/site-packages (from folium) (1.15.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from jinja2>=2.9->folium) (1.1.0)

Import URL content using _BeautifulSoup_

In [4]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
html = urlopen(url)
soup = BeautifulSoup(html, 'lxml')

In [5]:
print(soup.prettify()[0:700])

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of postal codes of Canada: M - Wikipedia
  </title>
  <script>
   document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"7f51de47-a8f2-4134-8071-f278674329c7","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"List_of_postal_codes_of_Canada:_M","wgTitle":"List of po

Find all rows in the table and save to the variable rows

In [6]:
rows = soup.find_all("tr")
rows[0:5]

[<tr>
 <th>Postal Code
 </th>
 <th>Borough
 </th>
 <th>Neighborhood
 </th></tr>, <tr>
 <td>M1A
 </td>
 <td>Not assigned
 </td>
 <td>Not assigned
 </td></tr>, <tr>
 <td>M2A
 </td>
 <td>Not assigned
 </td>
 <td>Not assigned
 </td></tr>, <tr>
 <td>M3A
 </td>
 <td>North York
 </td>
 <td>Parkwoods
 </td></tr>, <tr>
 <td>M4A
 </td>
 <td>North York
 </td>
 <td>Victoria Village
 </td></tr>]

Save the column names (header) to the list variable col

In [7]:
col = []
for r in rows[0].find_all("th"):
    col.append(r.string.strip('\n'))
print(col)

['Postal Code', 'Borough', 'Neighborhood']

Save the table contents in "rows" to the list variable in data

In [8]:
data = []
i = 1
for i in range(len(rows)):
    row = []
    for r in rows[i].find_all("td"):
            row.append(r.string)
    data.append(row)
    i+=1

In [9]:
del data[-4:]
del data[0]
print(data)

[['M1A\n', 'Not assigned\n', 'Not assigned\n'], ['M2A\n', 'Not assigned\n', 'Not assigned\n'], ['M3A\n', 'North York\n', 'Parkwoods\n'], ['M4A\n', 'North York\n', 'Victoria Village\n'], ['M5A\n', 'Downtown Toronto\n', 'Regent Park, Harbourfront\n'], ['M6A\n', 'North York\n', 'Lawrence Manor, Lawrence Heights\n'], ['M7A\n', 'Downtown Toronto\n', "Queen's Park, Ontario Provincial Government\n"], ['M8A\n', 'Not assigned\n', 'Not assigned\n'], ['M9A\n', 'Etobicoke\n', 'Islington Avenue, Humber Valley Village\n'], ['M1B\n', 'Scarborough\n', 'Malvern, Rouge\n'], ['M2B\n', 'Not assigned\n', 'Not assigned\n'], ['M3B\n', 'North York\n', 'Don Mills\n'], ['M4B\n', 'East York\n', 'Parkview Hill, Woodbine Gardens\n'], ['M5B\n', 'Downtown Toronto\n', 'Garden District, Ryerson\n'], ['M6B\n', 'North York\n', 'Glencairn\n'], ['M7B\n', 'Not assigned\n', 'Not assigned\n'], ['M8B\n', 'Not assigned\n', 'Not assigned\n'], ['M9B\n', 'Etobicoke\n', 'West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale\n'], ['M1C\n', 'Scarborough\n', 'Rouge Hill, Port Union, Highland Creek\n'], ['M2C\n', 'Not assigned\n', 'Not assigned\n'], ['M3C\n', 'North York\n', 'Don Mills\n'], ['M4C\n', 'East York\n', 'Woodbine Heights\n'], ['M5C\n', 'Downtown Toronto\n', 'St. James Town\n'], ['M6C\n', 'York\n', 'Humewood-Cedarvale\n'], ['M7C\n', 'Not assigned\n', 'Not assigned\n'], ['M8C\n', 'Not assigned\n', 'Not assigned\n'], ['M9C\n', 'Etobicoke\n', 'Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood\n'], ['M1E\n', 'Scarborough\n', 'Guildwood, Morningside, West Hill\n'], ['M2E\n', 'Not assigned\n', 'Not assigned\n'], ['M3E\n', 'Not assigned\n', 'Not assigned\n'], ['M4E\n', 'East Toronto\n', 'The Beaches\n'], ['M5E\n', 'Downtown Toronto\n', 'Berczy Park\n'], ['M6E\n', 'York\n', 'Caledonia-Fairbanks\n'], ['M7E\n', 'Not assigned\n', 'Not assigned\n'], ['M8E\n', 'Not assigned\n', 'Not assigned\n'], ['M9E\n', 'Not assigned\n', 'Not assigned\n'], ['M1G\n', 'Scarborough\n', 'Woburn\n'], ['M2G\n', 'Not assigned\n', 'Not assigned\n'], ['M3G\n', 'Not assigned\n', 'Not assigned\n'], ['M4G\n', 'East York\n', 'Leaside\n'], ['M5G\n', 'Downtown Toronto\n', 'Central Bay Street\n'], ['M6G\n', 'Downtown Toronto\n', 'Christie\n'], ['M7G\n', 'Not assigned\n', 'Not assigned\n'], ['M8G\n', 'Not assigned\n', 'Not assigned\n'], ['M9G\n', 'Not assigned\n', 'Not assigned\n'], ['M1H\n', 'Scarborough\n', 'Cedarbrae\n'], ['M2H\n', 'North York\n', 'Hillcrest Village\n'], ['M3H\n', 'North York\n', 'Bathurst Manor, Wilson Heights, Downsview North\n'], ['M4H\n', 'East York\n', 'Thorncliffe Park\n'], ['M5H\n', 'Downtown Toronto\n', 'Richmond, Adelaide, King\n'], ['M6H\n', 'West Toronto\n', 'Dufferin, Dovercourt Village\n'], ['M7H\n', 'Not assigned\n', 'Not assigned\n'], ['M8H\n', 'Not assigned\n', 'Not assigned\n'], ['M9H\n', 'Not assigned\n', 'Not assigned\n'], ['M1J\n', 'Scarborough\n', 'Scarborough Village\n'], ['M2J\n', 'North York\n', 'Fairview, Henry Farm, Oriole\n'], ['M3J\n', 'North York\n', 'Northwood Park, York University\n'], ['M4J\n', 'East York\n', 'East Toronto, Broadview North (Old East York)\n'], ['M5J\n', 'Downtown Toronto\n', 'Harbourfront East, Union Station, Toronto Islands\n'], ['M6J\n', 'West Toronto\n', 'Little Portugal, Trinity\n'], ['M7J\n', 'Not assigned\n', 'Not assigned\n'], ['M8J\n', 'Not assigned\n', 'Not assigned\n'], ['M9J\n', 'Not assigned\n', 'Not assigned\n'], ['M1K\n', 'Scarborough\n', 'Kennedy Park, Ionview, East Birchmount Park\n'], ['M2K\n', 'North York\n', 'Bayview Village\n'], ['M3K\n', 'North York\n', 'Downsview\n'], ['M4K\n', 'East Toronto\n', 'The Danforth West, Riverdale\n'], ['M5K\n', 'Downtown Toronto\n', 'Toronto Dominion Centre, Design Exchange\n'], ['M6K\n', 'West Toronto\n', 'Brockton, Parkdale Village, Exhibition Place\n'], ['M7K\n', 'Not assigned\n', 'Not assigned\n'], ['M8K\n', 'Not assigned\n', 'Not assigned\n'], ['M9K\n', 'Not assigned\n', 'Not assigned\n'], ['M1L\n', 'Scarborough\n', 'Golden Mile, Clairlea, Oakridge\n'], ['M2L\n', 'North York\n', 'York Mills, Silver Hills\n'], ['M3L\n', 'North York\n', 'Downsview\n'], ['M4L\n', 'East Toronto\n', 'India Bazaar, The Beaches West\n'], ['M5L\n', 'Downtown Toronto\n', 'Commerce Court, Victoria Hotel\n'], ['M6L\n', 'North York\n', 'North Park, Maple Leaf Park, Upwood Park\n'], ['M7L\n', 'Not assigned\n', 'Not assigned\n'], ['M8L\n', 'Not assigned\n', 'Not assigned\n'], ['M9L\n', 'North York\n', 'Humber Summit\n'], ['M1M\n', 'Scarborough\n', 'Cliffside, Cliffcrest, Scarborough Village West\n'], ['M2M\n', 'North York\n', 'Willowdale, Newtonbrook\n'], ['M3M\n', 'North York\n', 'Downsview\n'], ['M4M\n', 'East Toronto\n', 'Studio District\n'], ['M5M\n', 'North York\n', 'Bedford Park, Lawrence Manor East\n'], ['M6M\n', 'York\n', 'Del Ray, Mount Dennis, Keelsdale and Silverthorn\n'], ['M7M\n', 'Not assigned\n', 'Not assigned\n'], ['M8M\n', 'Not assigned\n', 'Not assigned\n'], ['M9M\n', 'North York\n', 'Humberlea, Emery\n'], ['M1N\n', 'Scarborough\n', 'Birch Cliff, Cliffside West\n'], ['M2N\n', 'North York\n', 'Willowdale, Willowdale East\n'], ['M3N\n', 'North York\n', 'Downsview\n'], ['M4N\n', 'Central Toronto\n', 'Lawrence Park\n'], ['M5N\n', 'Central Toronto\n', 'Roselawn\n'], ['M6N\n', 'York\n', 'Runnymede, The Junction North\n'], ['M7N\n', 'Not assigned\n', 'Not assigned\n'], ['M8N\n', 'Not assigned\n', 'Not assigned\n'], ['M9N\n', 'York\n', 'Weston\n'], ['M1P\n', 'Scarborough\n', 'Dorset Park, Wexford Heights, Scarborough Town Centre\n'], ['M2P\n', 'North York\n', 'York Mills West\n'], ['M3P\n', 'Not assigned\n', 'Not assigned\n'], ['M4P\n', 'Central Toronto\n', 'Davisville North\n'], ['M5P\n', 'Central Toronto\n', 'Forest Hill North & West, Forest Hill Road Park\n'], ['M6P\n', 'West Toronto\n', 'High Park, The Junction South\n'], ['M7P\n', 'Not assigned\n', 'Not assigned\n'], ['M8P\n', 'Not assigned\n', 'Not assigned\n'], ['M9P\n', 'Etobicoke\n', 'Westmount\n'], ['M1R\n', 'Scarborough\n', 'Wexford, Maryvale\n'], ['M2R\n', 'North York\n', 'Willowdale, Willowdale West\n'], ['M3R\n', 'Not assigned\n', 'Not assigned\n'], ['M4R\n', 'Central Toronto\n', 'North Toronto West,  Lawrence Park\n'], ['M5R\n', 'Central Toronto\n', 'The Annex, North Midtown, Yorkville\n'], ['M6R\n', 'West Toronto\n', 'Parkdale, Roncesvalles\n'], ['M7R\n', 'Mississauga\n', 'Canada Post Gateway Processing Centre\n'], ['M8R\n', 'Not assigned\n', 'Not assigned\n'], ['M9R\n', 'Etobicoke\n', 'Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens\n'], ['M1S\n', 'Scarborough\n', 'Agincourt\n'], ['M2S\n', 'Not assigned\n', 'Not assigned\n'], ['M3S\n', 'Not assigned\n', 'Not assigned\n'], ['M4S\n', 'Central Toronto\n', 'Davisville\n'], ['M5S\n', 'Downtown Toronto\n', 'University of Toronto, Harbord\n'], ['M6S\n', 'West Toronto\n', 'Runnymede, Swansea\n'], ['M7S\n', 'Not assigned\n', 'Not assigned\n'], ['M8S\n', 'Not assigned\n', 'Not assigned\n'], ['M9S\n', 'Not assigned\n', 'Not assigned\n'], ['M1T\n', 'Scarborough\n', "Clarks Corners, Tam O'Shanter, Sullivan\n"], ['M2T\n', 'Not assigned\n', 'Not assigned\n'], ['M3T\n', 'Not assigned\n', 'Not assigned\n'], ['M4T\n', 'Central Toronto\n', 'Moore Park, Summerhill East\n'], ['M5T\n', 'Downtown Toronto\n', 'Kensington Market, Chinatown, Grange Park\n'], ['M6T\n', 'Not assigned\n', 'Not assigned\n'], ['M7T\n', 'Not assigned\n', 'Not assigned\n'], ['M8T\n', 'Not assigned\n', 'Not assigned\n'], ['M9T\n', 'Not assigned\n', 'Not assigned\n'], ['M1V\n', 'Scarborough\n', "Milliken, Agincourt North, Steeles East, L'Amoreaux East\n"], ['M2V\n', 'Not assigned\n', 'Not assigned\n'], ['M3V\n', 'Not assigned\n', 'Not assigned\n'], ['M4V\n', 'Central Toronto\n', 'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park\n'], ['M5V\n', 'Downtown Toronto\n', 'CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport\n'], ['M6V\n', 'Not assigned\n', 'Not assigned\n'], ['M7V\n', 'Not assigned\n', 'Not assigned\n'], ['M8V\n', 'Etobicoke\n', 'New Toronto, Mimico South, Humber Bay Shores\n'], ['M9V\n', 'Etobicoke\n', 'South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens\n'], ['M1W\n', 'Scarborough\n', "Steeles West, L'Amoreaux West\n"], ['M2W\n', 'Not assigned\n', 'Not assigned\n'], ['M3W\n', 'Not assigned\n', 'Not assigned\n'], ['M4W\n', 'Downtown Toronto\n', 'Rosedale\n'], ['M5W\n', 'Downtown Toronto\n', 'Stn A PO Boxes\n'], ['M6W\n', 'Not assigned\n', 'Not assigned\n'], ['M7W\n', 'Not assigned\n', 'Not assigned\n'], ['M8W\n', 'Etobicoke\n', 'Alderwood, Long Branch\n'], ['M9W\n', 'Etobicoke\n', 'Northwest, West Humber - Clairville\n'], ['M1X\n', 'Scarborough\n', 'Upper Rouge\n'], ['M2X\n', 'Not assigned\n', 'Not assigned\n'], ['M3X\n', 'Not assigned\n', 'Not assigned\n'], ['M4X\n', 'Downtown Toronto\n', 'St. James Town, Cabbagetown\n'], ['M5X\n', 'Downtown Toronto\n', 'First Canadian Place, Underground city\n'], ['M6X\n', 'Not assigned\n', 'Not assigned\n'], ['M7X\n', 'Not assigned\n', 'Not assigned\n'], ['M8X\n', 'Etobicoke\n', 'The Kingsway, Montgomery Road, Old Mill North\n'], ['M9X\n', 'Not assigned\n', 'Not assigned\n'], ['M1Y\n', 'Not assigned\n', 'Not assigned\n'], ['M2Y\n', 'Not assigned\n', 'Not assigned\n'], ['M3Y\n', 'Not assigned\n', 'Not assigned\n'], ['M4Y\n', 'Downtown Toronto\n', 'Church and Wellesley\n'], ['M5Y\n', 'Not assigned\n', 'Not assigned\n'], ['M6Y\n', 'Not assigned\n', 'Not assigned\n'], ['M7Y\n', 'East Toronto\n', 'Business reply mail Processing Centre, South Central Letter Processing Plant Toronto\n'], ['M8Y\n', 'Etobicoke\n', "Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East\n"], ['M9Y\n', 'Not assigned\n', 'Not assigned\n'], ['M1Z\n', 'Not assigned\n', 'Not assigned\n'], ['M2Z\n', 'Not assigned\n', 'Not assigned\n'], ['M3Z\n', 'Not assigned\n', 'Not assigned\n'], ['M4Z\n', 'Not assigned\n', 'Not assigned\n'], ['M5Z\n', 'Not assigned\n', 'Not assigned\n'], ['M6Z\n', 'Not assigned\n', 'Not assigned\n'], ['M7Z\n', 'Not assigned\n', 'Not assigned\n'], ['M8Z\n', 'Etobicoke\n', 'Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West\n'], ['M9Z\n', 'Not assigned\n', 'Not assigned\n']]

Remove "\n" from the table contents and save to the new list variable ndata

In [10]:
ndata = []
for d in data:
    row = []
    for e in d:
        row.append(e.strip('\n'))
    ndata.append(row)
print(ndata)

[['M1A', 'Not assigned', 'Not assigned'], ['M2A', 'Not assigned', 'Not assigned'], ['M3A', 'North York', 'Parkwoods'], ['M4A', 'North York', 'Victoria Village'], ['M5A', 'Downtown Toronto', 'Regent Park, Harbourfront'], ['M6A', 'North York', 'Lawrence Manor, Lawrence Heights'], ['M7A', 'Downtown Toronto', "Queen's Park, Ontario Provincial Government"], ['M8A', 'Not assigned', 'Not assigned'], ['M9A', 'Etobicoke', 'Islington Avenue, Humber Valley Village'], ['M1B', 'Scarborough', 'Malvern, Rouge'], ['M2B', 'Not assigned', 'Not assigned'], ['M3B', 'North York', 'Don Mills'], ['M4B', 'East York', 'Parkview Hill, Woodbine Gardens'], ['M5B', 'Downtown Toronto', 'Garden District, Ryerson'], ['M6B', 'North York', 'Glencairn'], ['M7B', 'Not assigned', 'Not assigned'], ['M8B', 'Not assigned', 'Not assigned'], ['M9B', 'Etobicoke', 'West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale'], ['M1C', 'Scarborough', 'Rouge Hill, Port Union, Highland Creek'], ['M2C', 'Not assigned', 'Not assigned'], ['M3C', 'North York', 'Don Mills'], ['M4C', 'East York', 'Woodbine Heights'], ['M5C', 'Downtown Toronto', 'St. James Town'], ['M6C', 'York', 'Humewood-Cedarvale'], ['M7C', 'Not assigned', 'Not assigned'], ['M8C', 'Not assigned', 'Not assigned'], ['M9C', 'Etobicoke', 'Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood'], ['M1E', 'Scarborough', 'Guildwood, Morningside, West Hill'], ['M2E', 'Not assigned', 'Not assigned'], ['M3E', 'Not assigned', 'Not assigned'], ['M4E', 'East Toronto', 'The Beaches'], ['M5E', 'Downtown Toronto', 'Berczy Park'], ['M6E', 'York', 'Caledonia-Fairbanks'], ['M7E', 'Not assigned', 'Not assigned'], ['M8E', 'Not assigned', 'Not assigned'], ['M9E', 'Not assigned', 'Not assigned'], ['M1G', 'Scarborough', 'Woburn'], ['M2G', 'Not assigned', 'Not assigned'], ['M3G', 'Not assigned', 'Not assigned'], ['M4G', 'East York', 'Leaside'], ['M5G', 'Downtown Toronto', 'Central Bay Street'], ['M6G', 'Downtown Toronto', 'Christie'], ['M7G', 'Not assigned', 'Not assigned'], ['M8G', 'Not assigned', 'Not assigned'], ['M9G', 'Not assigned', 'Not assigned'], ['M1H', 'Scarborough', 'Cedarbrae'], ['M2H', 'North York', 'Hillcrest Village'], ['M3H', 'North York', 'Bathurst Manor, Wilson Heights, Downsview North'], ['M4H', 'East York', 'Thorncliffe Park'], ['M5H', 'Downtown Toronto', 'Richmond, Adelaide, King'], ['M6H', 'West Toronto', 'Dufferin, Dovercourt Village'], ['M7H', 'Not assigned', 'Not assigned'], ['M8H', 'Not assigned', 'Not assigned'], ['M9H', 'Not assigned', 'Not assigned'], ['M1J', 'Scarborough', 'Scarborough Village'], ['M2J', 'North York', 'Fairview, Henry Farm, Oriole'], ['M3J', 'North York', 'Northwood Park, York University'], ['M4J', 'East York', 'East Toronto, Broadview North (Old East York)'], ['M5J', 'Downtown Toronto', 'Harbourfront East, Union Station, Toronto Islands'], ['M6J', 'West Toronto', 'Little Portugal, Trinity'], ['M7J', 'Not assigned', 'Not assigned'], ['M8J', 'Not assigned', 'Not assigned'], ['M9J', 'Not assigned', 'Not assigned'], ['M1K', 'Scarborough', 'Kennedy Park, Ionview, East Birchmount Park'], ['M2K', 'North York', 'Bayview Village'], ['M3K', 'North York', 'Downsview'], ['M4K', 'East Toronto', 'The Danforth West, Riverdale'], ['M5K', 'Downtown Toronto', 'Toronto Dominion Centre, Design Exchange'], ['M6K', 'West Toronto', 'Brockton, Parkdale Village, Exhibition Place'], ['M7K', 'Not assigned', 'Not assigned'], ['M8K', 'Not assigned', 'Not assigned'], ['M9K', 'Not assigned', 'Not assigned'], ['M1L', 'Scarborough', 'Golden Mile, Clairlea, Oakridge'], ['M2L', 'North York', 'York Mills, Silver Hills'], ['M3L', 'North York', 'Downsview'], ['M4L', 'East Toronto', 'India Bazaar, The Beaches West'], ['M5L', 'Downtown Toronto', 'Commerce Court, Victoria Hotel'], ['M6L', 'North York', 'North Park, Maple Leaf Park, Upwood Park'], ['M7L', 'Not assigned', 'Not assigned'], ['M8L', 'Not assigned', 'Not assigned'], ['M9L', 'North York', 'Humber Summit'], ['M1M', 'Scarborough', 'Cliffside, Cliffcrest, Scarborough Village West'], ['M2M', 'North York', 'Willowdale, Newtonbrook'], ['M3M', 'North York', 'Downsview'], ['M4M', 'East Toronto', 'Studio District'], ['M5M', 'North York', 'Bedford Park, Lawrence Manor East'], ['M6M', 'York', 'Del Ray, Mount Dennis, Keelsdale and Silverthorn'], ['M7M', 'Not assigned', 'Not assigned'], ['M8M', 'Not assigned', 'Not assigned'], ['M9M', 'North York', 'Humberlea, Emery'], ['M1N', 'Scarborough', 'Birch Cliff, Cliffside West'], ['M2N', 'North York', 'Willowdale, Willowdale East'], ['M3N', 'North York', 'Downsview'], ['M4N', 'Central Toronto', 'Lawrence Park'], ['M5N', 'Central Toronto', 'Roselawn'], ['M6N', 'York', 'Runnymede, The Junction North'], ['M7N', 'Not assigned', 'Not assigned'], ['M8N', 'Not assigned', 'Not assigned'], ['M9N', 'York', 'Weston'], ['M1P', 'Scarborough', 'Dorset Park, Wexford Heights, Scarborough Town Centre'], ['M2P', 'North York', 'York Mills West'], ['M3P', 'Not assigned', 'Not assigned'], ['M4P', 'Central Toronto', 'Davisville North'], ['M5P', 'Central Toronto', 'Forest Hill North & West, Forest Hill Road Park'], ['M6P', 'West Toronto', 'High Park, The Junction South'], ['M7P', 'Not assigned', 'Not assigned'], ['M8P', 'Not assigned', 'Not assigned'], ['M9P', 'Etobicoke', 'Westmount'], ['M1R', 'Scarborough', 'Wexford, Maryvale'], ['M2R', 'North York', 'Willowdale, Willowdale West'], ['M3R', 'Not assigned', 'Not assigned'], ['M4R', 'Central Toronto', 'North Toronto West,  Lawrence Park'], ['M5R', 'Central Toronto', 'The Annex, North Midtown, Yorkville'], ['M6R', 'West Toronto', 'Parkdale, Roncesvalles'], ['M7R', 'Mississauga', 'Canada Post Gateway Processing Centre'], ['M8R', 'Not assigned', 'Not assigned'], ['M9R', 'Etobicoke', 'Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens'], ['M1S', 'Scarborough', 'Agincourt'], ['M2S', 'Not assigned', 'Not assigned'], ['M3S', 'Not assigned', 'Not assigned'], ['M4S', 'Central Toronto', 'Davisville'], ['M5S', 'Downtown Toronto', 'University of Toronto, Harbord'], ['M6S', 'West Toronto', 'Runnymede, Swansea'], ['M7S', 'Not assigned', 'Not assigned'], ['M8S', 'Not assigned', 'Not assigned'], ['M9S', 'Not assigned', 'Not assigned'], ['M1T', 'Scarborough', "Clarks Corners, Tam O'Shanter, Sullivan"], ['M2T', 'Not assigned', 'Not assigned'], ['M3T', 'Not assigned', 'Not assigned'], ['M4T', 'Central Toronto', 'Moore Park, Summerhill East'], ['M5T', 'Downtown Toronto', 'Kensington Market, Chinatown, Grange Park'], ['M6T', 'Not assigned', 'Not assigned'], ['M7T', 'Not assigned', 'Not assigned'], ['M8T', 'Not assigned', 'Not assigned'], ['M9T', 'Not assigned', 'Not assigned'], ['M1V', 'Scarborough', "Milliken, Agincourt North, Steeles East, L'Amoreaux East"], ['M2V', 'Not assigned', 'Not assigned'], ['M3V', 'Not assigned', 'Not assigned'], ['M4V', 'Central Toronto', 'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park'], ['M5V', 'Downtown Toronto', 'CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport'], ['M6V', 'Not assigned', 'Not assigned'], ['M7V', 'Not assigned', 'Not assigned'], ['M8V', 'Etobicoke', 'New Toronto, Mimico South, Humber Bay Shores'], ['M9V', 'Etobicoke', 'South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens'], ['M1W', 'Scarborough', "Steeles West, L'Amoreaux West"], ['M2W', 'Not assigned', 'Not assigned'], ['M3W', 'Not assigned', 'Not assigned'], ['M4W', 'Downtown Toronto', 'Rosedale'], ['M5W', 'Downtown Toronto', 'Stn A PO Boxes'], ['M6W', 'Not assigned', 'Not assigned'], ['M7W', 'Not assigned', 'Not assigned'], ['M8W', 'Etobicoke', 'Alderwood, Long Branch'], ['M9W', 'Etobicoke', 'Northwest, West Humber - Clairville'], ['M1X', 'Scarborough', 'Upper Rouge'], ['M2X', 'Not assigned', 'Not assigned'], ['M3X', 'Not assigned', 'Not assigned'], ['M4X', 'Downtown Toronto', 'St. James Town, Cabbagetown'], ['M5X', 'Downtown Toronto', 'First Canadian Place, Underground city'], ['M6X', 'Not assigned', 'Not assigned'], ['M7X', 'Not assigned', 'Not assigned'], ['M8X', 'Etobicoke', 'The Kingsway, Montgomery Road, Old Mill North'], ['M9X', 'Not assigned', 'Not assigned'], ['M1Y', 'Not assigned', 'Not assigned'], ['M2Y', 'Not assigned', 'Not assigned'], ['M3Y', 'Not assigned', 'Not assigned'], ['M4Y', 'Downtown Toronto', 'Church and Wellesley'], ['M5Y', 'Not assigned', 'Not assigned'], ['M6Y', 'Not assigned', 'Not assigned'], ['M7Y', 'East Toronto', 'Business reply mail Processing Centre, South Central Letter Processing Plant Toronto'], ['M8Y', 'Etobicoke', "Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East"], ['M9Y', 'Not assigned', 'Not assigned'], ['M1Z', 'Not assigned', 'Not assigned'], ['M2Z', 'Not assigned', 'Not assigned'], ['M3Z', 'Not assigned', 'Not assigned'], ['M4Z', 'Not assigned', 'Not assigned'], ['M5Z', 'Not assigned', 'Not assigned'], ['M6Z', 'Not assigned', 'Not assigned'], ['M7Z', 'Not assigned', 'Not assigned'], ['M8Z', 'Etobicoke', 'Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West'], ['M9Z', 'Not assigned', 'Not assigned']]

Create a dataframe with contents in ndata and column headers in col

In [11]:
df = pd.DataFrame(ndata, columns = col)
df.shape

(180, 3)

In [12]:
df

,Postal Code,Borough,Neighborhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
7,M8A,Not assigned,Not assigned
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
10,M2B,Not assigned,Not assigned
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
15,M7B,Not assigned,Not assigned
16,M8B,Not assigned,Not assigned
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
19,M2C,Not assigned,Not assigned
20,M3C,North York,Don Mills
21,M4C,East York,Woodbine Heights
22,M5C,Downtown Toronto,St. James Town
23,M6C,York,Humewood-Cedarvale
24,M7C,Not assigned,Not assigned
25,M8C,Not assigned,Not assigned
26,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
27,M1E,Scarborough,"Guildwood, Morningside, West Hill"
28,M2E,Not assigned,Not assigned
29,M3E,Not assigned,Not assigned
...,...,...,...
150,M7W,Not assigned,Not assigned
151,M8W,Etobicoke,"Alderwood, Long Branch"
152,M9W,Etobicoke,"Northwest, West Humber - Clairville"
153,M1X,Scarborough,Upper Rouge
154,M2X,Not assigned,Not assigned
155,M3X,Not assigned,Not assigned
156,M4X,Downtown Toronto,"St. James Town, Cabbagetown"
157,M5X,Downtown Toronto,"First Canadian Place, Underground city"
158,M6X,Not assigned,Not assigned
159,M7X,Not assigned,Not assigned
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
161,M9X,Not assigned,Not assigned
162,M1Y,Not assigned,Not assigned
163,M2Y,Not assigned,Not assigned
164,M3Y,Not assigned,Not assigned
165,M4Y,Downtown Toronto,Church and Wellesley
166,M5Y,Not assigned,Not assigned
167,M6Y,Not assigned,Not assigned
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
170,M9Y,Not assigned,Not assigned
171,M1Z,Not assigned,Not assigned
172,M2Z,Not assigned,Not assigned
173,M3Z,Not assigned,Not assigned
174,M4Z,Not assigned,Not assigned
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

Create a new dataframe toronto only containing rows needed for the project using the specified Postal Code

In [13]:
toronto = pd.DataFrame(columns = col)
pc = ['M5G','M2H','M4B','M1J','M4G','M4M','M1R','M9V','M9L','M5V','M1B','M5A']
for i in range(len(pc)):
    toronto = toronto.append(df.loc[df['Postal Code'] == pc[i], :])
toronto

,Postal Code,Borough,Neighborhood
40,M5G,Downtown Toronto,Central Bay Street
46,M2H,North York,Hillcrest Village
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
54,M1J,Scarborough,Scarborough Village
39,M4G,East York,Leaside
84,M4M,East Toronto,Studio District
108,M1R,Scarborough,"Wexford, Maryvale"
143,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
80,M9L,North York,Humber Summit
139,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
9,M1B,Scarborough,"Malvern, Rouge"
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"

In [14]:
toronto.reset_index(inplace=True)
toronto.drop(columns = 'index', inplace=True)
toronto

,Postal Code,Borough,Neighborhood
0,M5G,Downtown Toronto,Central Bay Street
1,M2H,North York,Hillcrest Village
2,M4B,East York,"Parkview Hill, Woodbine Gardens"
3,M1J,Scarborough,Scarborough Village
4,M4G,East York,Leaside
5,M4M,East Toronto,Studio District
6,M1R,Scarborough,"Wexford, Maryvale"
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
8,M9L,North York,Humber Summit
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
10,M1B,Scarborough,"Malvern, Rouge"
11,M5A,Downtown Toronto,"Regent Park, Harbourfront"

Import geospatial data that contains latitudes and longitudes of each neighborhood

In [15]:
geospatial_data = pd.read_csv('https://cocl.us/Geospatial_data')
geospatial_data

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
5           M1J  43.744734 -79.239476
6           M1K  43.727929 -79.262029
7           M1L  43.711112 -79.284577
8           M1M  43.716316 -79.239476
9           M1N  43.692657 -79.264848
10          M1P  43.757410 -79.273304
11          M1R  43.750072 -79.295849
12          M1S  43.794200 -79.262029
13          M1T  43.781638 -79.304302
14          M1V  43.815252 -79.284577
15          M1W  43.799525 -79.318389
16          M1X  43.836125 -79.205636
17          M2H  43.803762 -79.363452
18          M2J  43.778517 -79.346556
19          M2K  43.786947 -79.385975
20          M2L  43.757490 -79.374714
21          M2M  43.789053 -79.408493
22          M2N  43.770120 -79.408493
23          M2P  43.752758 -79.400049
24          M2R  43.782736 -79.442259
25          M3A  43.753259 -79.329656
26          M3B  43.745906 -79.352188
27          M3C  43.725900 -79.340923
28          M3H  43.754328 -79.442259
29          M3J  43.767980 -79.487262
..          ...        ...        ...
73          M6C  43.693781 -79.428191
74          M6E  43.689026 -79.453512
75          M6G  43.669542 -79.422564
76          M6H  43.669005 -79.442259
77          M6J  43.647927 -79.419750
78          M6K  43.636847 -79.428191
79          M6L  43.713756 -79.490074
80          M6M  43.691116 -79.476013
81          M6N  43.673185 -79.487262
82          M6P  43.661608 -79.464763
83          M6R  43.648960 -79.456325
84          M6S  43.651571 -79.484450
85          M7A  43.662301 -79.389494
86          M7R  43.636966 -79.615819
87          M7Y  43.662744 -79.321558
88          M8V  43.605647 -79.501321
89          M8W  43.602414 -79.543484
90          M8X  43.653654 -79.506944
91          M8Y  43.636258 -79.498509
92          M8Z  43.628841 -79.520999
93          M9A  43.667856 -79.532242
94          M9B  43.650943 -79.554724
95          M9C  43.643515 -79.577201
96          M9L  43.756303 -79.565963
97          M9M  43.724766 -79.532242
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

Create a dataframe coordinates that contains only the coordinates of the specified neighborhoods

In [16]:
coordinates = pd.DataFrame()
for i in range(len(pc)):
    coordinates = coordinates.append(geospatial_data.loc[geospatial_data['Postal Code'] == pc[i], :])
coordinates

    Postal Code   Latitude  Longitude
57          M5G  43.657952 -79.387383
17          M2H  43.803762 -79.363452
35          M4B  43.706397 -79.309937
5           M1J  43.744734 -79.239476
38          M4G  43.709060 -79.363452
43          M4M  43.659526 -79.340923
11          M1R  43.750072 -79.295849
101         M9V  43.739416 -79.588437
96          M9L  43.756303 -79.565963
68          M5V  43.628947 -79.394420
0           M1B  43.806686 -79.194353
53          M5A  43.654260 -79.360636

In [17]:
coordinates.reset_index(inplace=True)
coordinates.drop(columns = 'index', inplace=True)
coordinates

   Postal Code   Latitude  Longitude
0          M5G  43.657952 -79.387383
1          M2H  43.803762 -79.363452
2          M4B  43.706397 -79.309937
3          M1J  43.744734 -79.239476
4          M4G  43.709060 -79.363452
5          M4M  43.659526 -79.340923
6          M1R  43.750072 -79.295849
7          M9V  43.739416 -79.588437
8          M9L  43.756303 -79.565963
9          M5V  43.628947 -79.394420
10         M1B  43.806686 -79.194353
11         M5A  43.654260 -79.360636

Add latitude and longitude columns to the dataframe toronto

In [18]:
toronto['Latitude'] = coordinates['Latitude']
toronto['Longitude'] = coordinates['Longitude']
toronto

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
1,M2H,North York,Hillcrest Village,43.803762,-79.363452
2,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
3,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
4,M4G,East York,Leaside,43.709060,-79.363452
5,M4M,East Toronto,Studio District,43.659526,-79.340923
6,M1R,Scarborough,"Wexford, Maryvale",43.750072,-79.295849
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
8,M9L,North York,Humber Summit,43.756303,-79.565963
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
10,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
11,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636

Get the geographical coordinates of Toronto

In [19]:
address = 'Toronto, ON'
geolocator = Nominatim(user_agent="toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.

Visualize Toronto and the neighborhoods in it

In [20]:
map_toronto = folium.Map(location=[latitude, longitude], zoom_start=11)

for lat, lng, label in zip(toronto['Latitude'], toronto['Longitude'], toronto['Neighborhood']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

Define Foursquare Credentials and Version

__THE GOAL IS TO ANALYZE THE TYPES OF RESTAURANTS IN EACH NEIGHBORHOOD, CLUSTER THE NEIGHBORHOODS BY FREQUENCY OF VARIOUS TYPES OF RESTAURANTS SO TRAVELERS TO THE AREAS MARKED ABOVE CAN MAKE A BETTER DECISION ON WHICH NEIGHBORHOOD TO TRAVEL TO DEPENDING ON WHAT CUISINE THEY CRAVE.__

In [21]:
# The code was removed by Watson Studio for sharing.

CLIENT_ID, CLIENT_SECRET, and VERSION defined!

Create a function that generates URLs, make GET requests, import only relevent information for each venues and return a dataframe

In [22]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
        
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'],  
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

Run the getNearbyVenues function on each neighborhood and save to the dataframe toronto_venues

In [23]:
LIMIT = 100
toronto_venues = getNearbyVenues(names=toronto['Neighborhood'],
                                 latitudes=toronto['Latitude'],
                                 longitudes=toronto['Longitude']
                                 )

Central Bay Street
Hillcrest Village
Parkview Hill, Woodbine Gardens
Scarborough Village
Leaside
Studio District
Wexford, Maryvale
South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens
Humber Summit
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
Malvern, Rouge
Regent Park, Harbourfront

In [24]:
print(toronto_venues.shape)
toronto_venues.head()

(233, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Central Bay Street,43.657952,-79.387383,Jimmy's Coffee,43.658421,-79.385613,Coffee Shop
1,Central Bay Street,43.657952,-79.387383,Somethin' 2 Talk About,43.658395,-79.385338,Middle Eastern Restaurant
2,Central Bay Street,43.657952,-79.387383,Neo Coffee Bar,43.660140,-79.385870,Coffee Shop
3,Central Bay Street,43.657952,-79.387383,Hailed Coffee,43.658833,-79.383684,Coffee Shop
4,Central Bay Street,43.657952,-79.387383,Panago,43.658258,-79.384313,Pizza Place

Venues count for each neighborhood

In [25]:
toronto_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
"CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport",15,15,15,15,15,15
Central Bay Street,65,65,65,65,65,65
Hillcrest Village,5,5,5,5,5,5
Humber Summit,2,2,2,2,2,2
Leaside,34,34,34,34,34,34
"Malvern, Rouge",1,1,1,1,1,1
"Parkview Hill, Woodbine Gardens",12,12,12,12,12,12
"Regent Park, Harbourfront",44,44,44,44,44,44
Scarborough Village,1,1,1,1,1,1
"South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens",9,9,9,9,9,9
Studio District,40,40,40,40,40,40
"Wexford, Maryvale",5,5,5,5,5,5

Number of unique venue categories

In [26]:
len(toronto_venues['Venue Category'].unique())

108

Create a new dataframe toronto_onehot with dummies for each venue category

In [27]:
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

toronto_onehot.head()

,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Art Gallery,Art Museum,...,Sporting Goods Shop,Sports Bar,Stationery Store,Supermarket,Sushi Restaurant,Thai Restaurant,Theater,Vegetarian / Vegan Restaurant,Wine Bar,Yoga Studio
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Drop all venue categories that are not restaurant

In [28]:
toronto_onehot = toronto_onehot[toronto_onehot.columns[toronto_onehot.columns.str.contains('Restaurant')]]

Add Neighborhood column from toronto_venues as the first column

In [29]:
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]
toronto_onehot.head()

,Neighborhood,American Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant,...,Mediterranean Restaurant,Mexican Restaurant,Middle Eastern Restaurant,Modern European Restaurant,New American Restaurant,Restaurant,Seafood Restaurant,Sushi Restaurant,Thai Restaurant,Vegetarian / Vegan Restaurant
0,Central Bay Street,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Central Bay Street,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,Central Bay Street,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Central Bay Street,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Central Bay Street,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
toronto_onehot.shape

(233, 22)

Make a new dataframe toronto_grouped with grouped rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [31]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

,Neighborhood,American Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant,...,Mediterranean Restaurant,Mexican Restaurant,Middle Eastern Restaurant,Modern European Restaurant,New American Restaurant,Restaurant,Seafood Restaurant,Sushi Restaurant,Thai Restaurant,Vegetarian / Vegan Restaurant
0,"CN Tower, King and Spadina, Railway Lands, Har...",0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Central Bay Street,0.00,0.000000,0.000,0.015385,0.000000,0.015385,0.015385,0.061538,0.046154,...,0.0,0.000000,0.015385,0.015385,0.015385,0.000000,0.015385,0.015385,0.030769,0.015385
2,Hillcrest Village,0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Humber Summit,0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Leaside,0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.029412,0.000000,0.000000,0.000000,0.029412,0.000000,0.029412,0.000000,0.000000
5,"Malvern, Rouge",0.00,0.000000,0.000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,"Parkview Hill, Woodbine Gardens",0.00,0.000000,0.000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,"Regent Park, Harbourfront",0.00,0.022727,0.000,0.000000,0.000000,0.022727,0.000000,0.000000,0.000000,...,0.0,0.022727,0.000000,0.000000,0.000000,0.045455,0.000000,0.000000,0.000000,0.000000
8,Scarborough Village,0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,"South Steeles, Silverstone, Humbergate, Jamest...",0.00,0.000000,0.000,0.000000,0.111111,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,Studio District,0.05,0.000000,0.025,0.000000,0.000000,0.000000,0.000000,0.025000,0.000000,...,0.0,0.000000,0.025000,0.000000,0.000000,0.000000,0.025000,0.000000,0.025000,0.000000
11,"Wexford, Maryvale",0.00,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [32]:
toronto_grouped.shape

(12, 22)

Write a function to sort the rows in descending order

In [33]:
def return_most_common_restaurants(row, num_top_restaurants):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_restaurants]

Create a dataframe neighborhoods_venues_sorted with top 10 venue categories for each neighborhood

In [34]:
num_top_restaurants = 10
indicators = ['st', 'nd', 'rd']

columns = ['Neighborhood']
for ind in np.arange(num_top_restaurants):
    try:
        columns.append('{}{} Most Common Restaurant'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Restaurant'.format(ind+1))

neighborhoods_restaurants_sorted = pd.DataFrame(columns=columns)
neighborhoods_restaurants_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_restaurants_sorted.iloc[ind, 1:] = return_most_common_restaurants(toronto_grouped.iloc[ind, :], num_top_restaurants)

neighborhoods_restaurants_sorted

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
0,"CN Tower, King and Spadina, Railway Lands, Har...",Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
1,Central Bay Street,Italian Restaurant,Japanese Restaurant,Thai Restaurant,Vegetarian / Vegan Restaurant,Sushi Restaurant,Seafood Restaurant,New American Restaurant,Modern European Restaurant,Middle Eastern Restaurant,Falafel Restaurant
2,Hillcrest Village,Mediterranean Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant
3,Humber Summit,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
4,Leaside,Sushi Restaurant,Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant
5,"Malvern, Rouge",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
6,"Parkview Hill, Woodbine Gardens",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
7,"Regent Park, Harbourfront",Restaurant,Asian Restaurant,French Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,Indian Restaurant
8,Scarborough Village,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
9,"South Steeles, Silverstone, Humbergate, Jamest...",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
10,Studio District,American Restaurant,Middle Eastern Restaurant,Comfort Food Restaurant,Italian Restaurant,Thai Restaurant,Latin American Restaurant,Seafood Restaurant,Modern European Restaurant,New American Restaurant,Mexican Restaurant
11,"Wexford, Maryvale",Middle Eastern Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant

Run k-means clustering and cluster the neighborhoods into 5 clusters by restaurant types

In [35]:
kclusters = 5
toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

kmeans.labels_[0:10]

array([1, 1, 3, 1, 1, 2, 0, 1, 1, 0], dtype=int32)

Create a new dataframe by merging toronto and neighborhoods_venues_sorted and dropping postal codes column, which returns only boroughs, neighborhoods, coordinates for each neighborhood, newly-added cluster labels, and venue categories

In [36]:
neighborhoods_restaurants_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

toronto_merged = toronto
toronto_merged = toronto_merged.join(neighborhoods_restaurants_sorted.set_index('Neighborhood'), on='Neighborhood')

toronto_merged.drop(columns = 'Postal Code', inplace=True)
toronto_merged

,Borough,Neighborhood,Latitude,Longitude,Cluster Labels,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
0,Downtown Toronto,Central Bay Street,43.657952,-79.387383,1,Italian Restaurant,Japanese Restaurant,Thai Restaurant,Vegetarian / Vegan Restaurant,Sushi Restaurant,Seafood Restaurant,New American Restaurant,Modern European Restaurant,Middle Eastern Restaurant,Falafel Restaurant
1,North York,Hillcrest Village,43.803762,-79.363452,3,Mediterranean Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant
2,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937,0,Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
3,Scarborough,Scarborough Village,43.744734,-79.239476,1,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
4,East York,Leaside,43.709060,-79.363452,1,Sushi Restaurant,Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant
5,East Toronto,Studio District,43.659526,-79.340923,1,American Restaurant,Middle Eastern Restaurant,Comfort Food Restaurant,Italian Restaurant,Thai Restaurant,Latin American Restaurant,Seafood Restaurant,Modern European Restaurant,New American Restaurant,Mexican Restaurant
6,Scarborough,"Wexford, Maryvale",43.750072,-79.295849,4,Middle Eastern Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant
7,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437,0,Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
8,North York,Humber Summit,43.756303,-79.565963,1,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
9,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420,1,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
10,Scarborough,"Malvern, Rouge",43.806686,-79.194353,2,Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
11,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636,1,Restaurant,Asian Restaurant,French Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,Indian Restaurant

Create a map that visualizes the resulting clusters

In [37]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

__THE FOLLOWING IS THE EXAMINATION OF EACH CLUSTER, SHOWING WHICH TYPES OF RESTAURANTS ARE FREQUENTLY POPULATED IN LISTED NEIGHBORHOODS. FOR THOSE WHO PLAN TO TRAVEL TO THE LISTED AREAS, THE FOLLOWING ANALYSIS SHOULD COME IN HANDY WHEN DECIDING WHICH NEIGHBORHOOD TO TRAVEL TO DEPENDING ON THE TYPE OF CUISINE YOU ARE CRAVING.__

__Cluster 1__: Mainly comprised of __Fast Food__, __Vegetarian/Vegan__, __Korean__, __Asian__, __Comfort Food Restaurants__, etc.

In [38]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
2,"Parkview Hill, Woodbine Gardens",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
7,"South Steeles, Silverstone, Humbergate, Jamest...",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant

__Cluster 2__: Mainly comprised of __Italian__, __Vegetarian/Vegan__, __Asian__, __Japanese__, __Korean__, __Comfort Food Restaurants__, etc.

In [39]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
0,Central Bay Street,Italian Restaurant,Japanese Restaurant,Thai Restaurant,Vegetarian / Vegan Restaurant,Sushi Restaurant,Seafood Restaurant,New American Restaurant,Modern European Restaurant,Middle Eastern Restaurant,Falafel Restaurant
3,Scarborough Village,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
4,Leaside,Sushi Restaurant,Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant
5,Studio District,American Restaurant,Middle Eastern Restaurant,Comfort Food Restaurant,Italian Restaurant,Thai Restaurant,Latin American Restaurant,Seafood Restaurant,Modern European Restaurant,New American Restaurant,Mexican Restaurant
8,Humber Summit,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
9,"CN Tower, King and Spadina, Railway Lands, Har...",Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant
11,"Regent Park, Harbourfront",Restaurant,Asian Restaurant,French Restaurant,Mexican Restaurant,Vegetarian / Vegan Restaurant,Japanese Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,Indian Restaurant

__Cluster 3__: Mainly comprised of __Fast Food__,__Vegetarian/Vegan__, __Korean__, __Asian Restaurants__ etc.

In [40]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
10,"Malvern, Rouge",Fast Food Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant,Japanese Restaurant

__Cluster 4__: Mainly comprised of __Middle Eastern__, __Vegetarian/Vegan__, __Korean__, __Asian__, __Comfort Food Restaurants__, etc.

In [41]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
1,Hillcrest Village,Mediterranean Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant

__Cluster 5__: Mainly comprised of __Mediterranean__, __Vegetarian/Vegan__, __Korean__, __Asian__, __Comfort Food Restaurants__, etc.

In [42]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Restaurant,2nd Most Common Restaurant,3rd Most Common Restaurant,4th Most Common Restaurant,5th Most Common Restaurant,6th Most Common Restaurant,7th Most Common Restaurant,8th Most Common Restaurant,9th Most Common Restaurant,10th Most Common Restaurant
6,"Wexford, Maryvale",Middle Eastern Restaurant,Vegetarian / Vegan Restaurant,Korean Restaurant,Asian Restaurant,Comfort Food Restaurant,Falafel Restaurant,Fast Food Restaurant,French Restaurant,Indian Restaurant,Italian Restaurant